application:
  version: ${version}

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
    info:
      enabled: true

info.app:
  name: "ECCAIRS Service"
  description: "This is the ECCAIRS Service to manage and serve taxonomies."
  version: ${version}

spring:
  output:
    ansi:
      enabled: DETECT
  servlet:
    multipart:
      max-request-size: '200000KB'
      max-file-size: '200000KB'

server:
  port: 18080
  servlet:
    contextPath: /eccairs-service

logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%X{username}] [thread] %-5level %logger{36} - %msg %n%throwable"
  level:
    root: INFO

eccairs:
  # Base URI for creating new IRIs
  baseUri: http://onto.fel.cvut.cz/ontologies/
  # SPARQL Query Protocol endpoint
  sparqlQueryEndpoint: http://localhost:8080/rdf4j-server/repositories/eccairs-aviation-4.1.0.7
  # SPARQL Graph Store Protocol endpoint template. Appending a named graph yields a GSP endpoint
  sparqlGspEndpointTemplate: http://localhost:8080/rdf4j-server/repositories/eccairs-aviation-4.1.0.7/rdf-graphs/service?graph=
